language: ruby

rvm:
  - 2.2.1

services:
  - postgresql

before_script:
  - createdb test_vgbot
  - bundle exec rake db:migrate

env:
  global:
    RAILS_ENV: test
    TRAVIS: true

sudo: false
cache: bundler

