language: ruby

rvm:
  - 2.2.1

services:
  - postgresql

before_script:
  - createdb test_vgbot
  - bundle exec rake db:migrate

script:
  - bundle exec rake && bundle exec rake jasmine:ci

env:
  global:
    RAILS_ENV: test
    TRAVIS: true

sudo: false
cache: bundler

