name: Great American Voter Guide National

view: national
folder: avg
layout: avg
publisher_class: Innactive
publisher_resource: nil
publisher_type: web

inherits: archived/2016_default

available_pages: 30
filler_pages: 0

contests:
  per_page: 1

measures:
  per_page: 1

candidates:
  max: 4

fields: []
