
name: Default Voter Guide

screenshot: default.png

contests: 4
candidates: 4
questions: 7
endorsements: 3
ballot_measures: 4

fields:
  -
    label: Title Page Header
    placeholder: The title that will appear on the front page of your guide
    element: input
    example: 2016 Chicago Voter Guide
    example_elem: h1
    limit: 40
    name: title_page_header
  -
    label: Title Page Subheader
    placeholder: The line right below the title, usually reminds people to vote
    example: Be Sure to Vote By November 8th
    element: input
    example_elem: h2
    limit: 40
    name: title_page_subheader
  -
    label: Title Page Blurb
    placeholder: A little bit about voting and the guide
    example: Your secret ballot means it’s all yours to decide. But hopefully this independent local nonprofit-prepared info helps.
    element: textarea
    limit: 120
    name: title_page_blurb
  -
    label: About Us Blurb
    placeholder: A note about your organization and what you do
    example: New Era Colorado Action Fund is a local non-partisan, non-profit organization reinventing politics for our generation through innovative social and political action. We inspire young Coloradans to move our state forward, engaging our generation in our city- and state-level democracy. New Era Colorado Action Fund is a 501(c)4 non-profit organization. You can learn more or sign up to volunteer at NewEraColoradoAction.org.
    element: textarea
    limit: 320
    name: about_us_blurb
  -
    label: Logo
    placeholder: Your logo - will need to work up to 200px
    example: /example_logo.png
    example_elem: img
    example_attr: src
    example_props:
        width: 120px
    element: ImageComponent
    name: about_us_logo
  -
    label: What You've Got to Bring To Vote
    placeholder: A paragraph explaining what you need to bring to vote
    example: To avoid issues on Election Day, or if you are a first time voter, we recommend you bring some form of identification. Options for what you can bring to prove identity and residency.
    element: textarea
    limit: 230
    name: what_you_got_to_bring
  -
    label: Where You've Got To Go
    placeholder: A paragraph explaining where you need to go to vote
    example: From February 29 through March 12, all 51 Early Voting sites will be open Monday through Saturday from 9am - 5pm. Go to chicagoelections.com to find a location near you. Please bring a government photo ID during early voting. For both “Grace Period” and “Early Voting” you will register and vote in the same day. To find polling locations for Election Day or early voting go to chicagoelections.com
    element: textarea
    limit: 275
    name: where_you_got_to_go
  -
    label: Find Out More
    placeholder: A paragraph explaining the guide and pointing to more information
    example: This independent voter guide is designed to give you the quickest, most important information on what you’re facing on your ballot and why it’s important to vote. But obviously there’s a lot more  information out there. If you’re looking to read more, we highly encourage checking out our bigger, online guide
    element: textarea
    limit: 350
    name: find_out_more
  -
    label: Partners
    placeholder: Thank the people and organizations the made this happen
    example: Also, lots more good info from our partners
    element: input
    limit: 50
    name: partners_list

question_seeds:
  -
    text: Do you support incentivizing local and state governments setting benchmarks for investments in women- and minority- owned business enterprises?
    tag: Economy
  -
    text: Do you support introducing small dollar public financing to decrease the influence of money in politics?
    tag: Voting Rights
  -
    text: Do you support eliminating domestic tax loopholes that reduce tax revenue that could fund infrastructure and education?
    tag: Economy
  -
    text: Do you support lowering the voting age in local and municipal elections to 16?
    tag: Voting Rights


question_tags:
  - Climate
  - Criminal Justice Reform
  - Drug Policy
  - Economy
  - Education
  - Healthcare
  - Immigration
  - LGBT
  - Reproduction Rights
  - Voting Rights
