
name: Default Voter Guide

screenshot: default.png
view: default
layout: default_layout

contests:
  partial: contest_large
  max: 4
  pages: 2

candidates:
  max: 4

measures:
  max: 4

endorsements:
  max: 3

questions:
  max: 7
  text:
    limit: 140
  samples:
    -
      text: Do you support boosting the use of clean energy?
      tag: Climate
    -
      text: Do you support taking government action to reduce the pollution that causes global warming?
      tag: Climate
    -
      text: Do you support regulating fracking more closely?
      tag: Climate
    -
      text: Do you support encouraging colleges and pension funds to divest from fossil fuels?
      tag: Climate
    -
      text: Do you support setting benchmarks for investments in women and minority owned businesses?
      tag: Economy
    -
      text: Do you support eliminating domestic tax loopholes that reduce tax revenue that could fund infrastructure and education?
      tag: Economy
    -
      text: Do you support guaranteeing people who do the same work part-time and full-time are paid the same for the hours they work?
      tag: Economy
    -
      text: Do you support ensuring more stable work hours like providing enough notice of work schedules, compensating working people for last-minute shift changes and cancellations?
      tag: Economy
    -
      text: Do you support ensuring working people have healthy work hours with enough rest between shifts and work weeks?
      tag: Economy
    -
      text: Do you support will you support policies that protect working people from being penalized for changing their availability or making a scheduling accommodation request?
      tag: Economy
    -
      text: Do you support making corporations give  hourly workers their schedules at least two weeks in advance?
      tag: Economy
    -
      text: Do you support allowing under-employed part-time workers to qualify for unemployment & housing assistance?
      tag: Economy
    -
      text: Do you support building a universal high-quality early childhood education system available to parents in low-wage service jobs who work irregular hours?
      tag: Economy
    -
      text: Do you support increased investment in schools, highways, and other infrastructure as a federal jobs program?
      tag: Economy
    -
      text: Do you support lowering how much the government spends on imprisoning people?
      tag: Economy
    -
      text: Do you support raising taxes on people making over $250,000?
      tag: Economy
    -
      text: Do you support prosecuting businesses that steal wages or tips from workers?
      tag: Economy
    -
      text: Do you support the government helping refinance mortgages at lower and more affordable rates?
      tag: Economy
    -
      text: Do you support removing barriers to employment for people trying to restart their lives after finishing their prison terms?
      tag: Economy
    -
      text: Do you support guaranteeing a living income regardless of employment status?
      tag: Economy
    -
      text: Do you support paying every worker in America at least $15 per hour?
      tag: Economy
    -
      text: Do you support making college free for students from families making less than $125,000?
      tag: Education
    -
      text: Do you support allowing recent college graduates to refinance student loans?
      tag: Education
    -
      text: Do you support ending “Broken Windows” policing that spends more energy on arrests for loitering and graffiti over major crimes?
      tag: Criminal Justice Reform
    -
      text: Do you support increasing job training programs?
      tag: Criminal Justice Reform
    -
      text: Do you support offering alternatives to incarceration for low level offenses such as - traffic violations, and low level drug offenses?
      tag: Criminal Justice Reform
    -
      text: Do you support decriminalizing offenses that pose no safety threat and that have historically targeted Black and brown communities?
      tag: Criminal Justice Reform
    -
      text: Do you support reparations for slavery, Jim Crow laws, and/or victims of state (Or police depending on need of specificity) violence?
      tag: Criminal Justice Reform
    -
      text: Do you support would you support removing police presence from schools?
      tag: Criminal Justice Reform
    -
      text: Do you support moving government money from policing to schools and jobs programs?
      tag: Criminal Justice Reform
    -
      text: Do you support making police report data on who they target for stops, arrests and who they use force against?
      tag: Criminal Justice Reform
    -
      text: Do you support making prosecutors report data on who they choose to prosecute, for what offenses and what plea bargains they offer?
      tag: Criminal Justice Reform
    -
      text: Do you support cities offering ID Cards to all residents, regardless of immigration status and gender identity?*
      tag: Immigration
    -
      text: Do you support providing free legal support to immigrants in deportation proceedings?
      tag: Immigration
    -
      text: Do you support not letting local police help Immigration Customs and Enforcement (ICE) deport immigrant families?
      tag: Immigration
    -
      text: Do you support the government making sure eligible immigrants know about services to become citizens?
      tag: Immigration
    -
      text: Do you support giving non-citizens the right to vote in local elections?
      tag: Immigration
    -
      text: Do you support tacking if police do racial profiling, and holding them accountable if they do?
      tag: Immigration
    -
      text: Do you support limiting the number of people who get deported rather than sentenced to serve time, if convicted of a crime?
      tag: Immigration
    -
      text: Do you support the government providing or ensuring housing for LGBTQ youth facing homelessness?
      tag: LGBT
    -
      text: Do you support allowing transgender youth to attend school, use facilities, and participate in programs that match the gender they identify as?
      tag: LGBT
    -
      text: Do you support protecting LGBTQ people from discrimination in housing, employment, and public serving spaces/businesses like restaurants and taxis?
      tag: LGBT
    -
      text: Do you support banning anti-gay conversion "therapy"?
      tag: LGBT
    -
      text: Do you support lifting the ban on gay and bisexual men donating blood?
      tag: LGBT
    -
      text: Do you support allowing transgender youth to attend school, use facilities, and participate in programs that match the gender they identify as?
      tag: LGBT
    -
      text: Do you support nondiscrimination protections for LGBTQ people in housing, employment, and public serving spaces/businesses like restaurants and taxis?
      tag: LGBT
    -
      text: Do you support the government providing or ensuring housing for LGBTQ youth facing homelessness?
      tag: LGBT
    -
      text: Do you support introducing small dollar public financing to decrease the influence of money in politics?
      tag: Voting Rights
    -
      text: Do you support lowering the voting age in local and municipal elections to 16?
      tag: Voting Rights
    -
      text: Do you support restoring voting rights to citizens who have been in prison, or are currently in prison?
      tag: Voting Rights
    -
      text: Do you support automatically and securely registering every eligible citizen to vote?
      tag: Voting Rights
    -
      text: Do you support offering every citizen the option to early vote, vote by mail, or register and vote on Election Day?
      tag: Voting Rights
    -
      text: Do you support a constitutional amendment overturning Citizens United and limiting private money in campaign finance?
      tag: Voting Rights

fields:
  -
    label: Title Page Header
    placeholder: The title that will appear on the front page of your guide
    element: input
    example: 2016 Chicago Voter Guide
    example_elem: h1
    limit: 40
    name: title_page_header
  -
    label: Title Page Subheader
    placeholder: The line right below the title, usually reminds people to vote
    example: Be Sure to Vote By November 8th
    element: input
    example_elem: h2
    limit: 40
    name: title_page_subheader
  -
    label: Title Page Blurb
    placeholder: A little bit about voting and the guide
    example: Your secret ballot means it’s all yours to decide. But hopefully this independent local nonprofit-prepared info helps.
    element: textarea
    limit: 120
    name: title_page_blurb
  -
    label: About Us Blurb
    placeholder: A note about your organization and what you do
    example: New Era Colorado Action Fund is a local non-partisan, non-profit organization reinventing politics for our generation through innovative social and political action. We inspire young Coloradans to move our state forward, engaging our generation in our city- and state-level democracy. New Era Colorado Action Fund is a 501(c)4 non-profit organization. You can learn more or sign up to volunteer at NewEraColoradoAction.org.
    element: textarea
    limit: 320
    name: about_us_blurb
  -
    label: Logo
    placeholder: Your logo - will need to work up to 200px
    example: /example_logo.png
    example_elem: img
    example_attr: src
    example_props:
        width: 120px
    element: ImageComponent
    name: about_us_logo
  -
    label: What You've Got to Bring To Vote
    placeholder: A paragraph explaining what you need to bring to vote
    example: To avoid issues on Election Day, or if you are a first time voter, we recommend you bring some form of identification. Options for what you can bring to prove identity and residency.
    element: textarea
    limit: 230
    name: what_you_got_to_bring
  -
    label: Where You've Got To Go
    placeholder: A paragraph explaining where you need to go to vote
    example: From February 29 through March 12, all 51 Early Voting sites will be open Monday through Saturday from 9am - 5pm. Go to chicagoelections.com to find a location near you. Please bring a government photo ID during early voting. For both “Grace Period” and “Early Voting” you will register and vote in the same day. To find polling locations for Election Day or early voting go to chicagoelections.com
    element: textarea
    limit: 275
    name: where_you_got_to_go
  -
    label: Find Out More
    placeholder: A paragraph explaining the guide and pointing to more information
    example: This independent voter guide is designed to give you the quickest, most important information on what you’re facing on your ballot and why it’s important to vote. But obviously there’s a lot more  information out there. If you’re looking to read more, we highly encourage checking out our bigger, online guide
    element: textarea
    limit: 350
    name: find_out_more
  -
    label: Partners
    placeholder: Thank the people and organizations the made this happen
    example: Also, lots more good info from our partners
    element: input
    limit: 50
    name: partners_list

tags:
  - Climate
  - Criminal Justice Reform
  - Drug Policy
  - Economy
  - Education
  - Healthcare
  - Immigration
  - LGBT
  - Reproduction Rights
  - Voting Rights
