
name: Default Voter Guide

screenshot: default.png
view: guide

available_pages: 10
filler_pages: 4

contests:
  partial: contest_large
  per_page:
    key: contest_layout
    values:
      contest_large: 2
      contest_small: 1

candidates:
  max: 4

measures:
  per_page: 1
  title:
    limit: 104

endorsements:
  max: 3

questions:
  max: 7
  text:
    limit: 140
  samples:
    -
      text: boosting the use of clean energy?
      tag: Climate
    -
      text: taking government action to reduce the pollution that causes global warming?
      tag: Climate
    -
      text: regulating fracking more closely?
      tag: Climate
    -
      text: encouraging colleges and pension funds to divest from fossil fuels?
      tag: Climate
    -
      text: setting benchmarks for investments in women and minority owned businesses?
      tag: Economy
    -
      text: eliminating domestic tax loopholes that reduce tax revenue that could fund infrastructure and education?
      tag: Economy
    -
      text: guaranteeing people who do the same work part-time and full-time are paid the same for the hours they work?
      tag: Economy
    -
      text: ensuring more stable work hours like providing enough notice of work schedules, compensating working people for last-minute shift changes and cancellations?
      tag: Economy
    -
      text: ensuring working people have healthy work hours with enough rest between shifts and work weeks?
      tag: Economy
    -
      text: will you support policies that protect working people from being penalized for changing their availability or making a scheduling accommodation request?
      tag: Economy
    -
      text: making corporations give  hourly workers their schedules at least two weeks in advance?
      tag: Economy
    -
      text: allowing under-employed part-time workers to qualify for unemployment & housing assistance?
      tag: Economy
    -
      text: building a universal high-quality early childhood education system available to parents in low-wage service jobs who work irregular hours?
      tag: Economy
    -
      text: increased investment in schools, highways, and other infrastructure as a federal jobs program?
      tag: Economy
    -
      text: lowering how much the government spends on imprisoning people?
      tag: Economy
    -
      text: raising taxes on people making over $250,000?
      tag: Economy
    -
      text: prosecuting businesses that steal wages or tips from workers?
      tag: Economy
    -
      text: the government helping refinance mortgages at lower and more affordable rates?
      tag: Economy
    -
      text: removing barriers to employment for people trying to restart their lives after finishing their prison terms?
      tag: Economy
    -
      text: guaranteeing a living income regardless of employment status?
      tag: Economy
    -
      text: paying every worker in America at least $15 per hour?
      tag: Economy
    -
      text: making college free for students from families making less than $125,000?
      tag: Education
    -
      text: allowing recent college graduates to refinance student loans?
      tag: Education
    -
      text: ending “Broken Windows” policing that spends more energy on arrests for loitering and graffiti over major crimes?
      tag: Criminal Justice Reform
    -
      text: increasing job training programs?
      tag: Criminal Justice Reform
    -
      text: offering alternatives to incarceration for low level offenses such as - traffic violations, and low level drug offenses?
      tag: Criminal Justice Reform
    -
      text: decriminalizing offenses that pose no safety threat and that have historically targeted Black and brown communities?
      tag: Criminal Justice Reform
    -
      text: reparations for slavery, Jim Crow laws, and/or victims of state (Or police depending on need of specificity) violence?
      tag: Criminal Justice Reform
    -
      text: would you support removing police presence from schools?
      tag: Criminal Justice Reform
    -
      text: moving government money from policing to schools and jobs programs?
      tag: Criminal Justice Reform
    -
      text: making police report data on who they target for stops, arrests and who they use force against?
      tag: Criminal Justice Reform
    -
      text: making prosecutors report data on who they choose to prosecute, for what offenses and what plea bargains they offer?
      tag: Criminal Justice Reform
    -
      text: cities offering ID Cards to all residents, regardless of immigration status and gender identity?*
      tag: Immigration
    -
      text: providing free legal support to immigrants in deportation proceedings?
      tag: Immigration
    -
      text: not letting local police help Immigration Customs and Enforcement (ICE) deport immigrant families?
      tag: Immigration
    -
      text: the government making sure eligible immigrants know about services to become citizens?
      tag: Immigration
    -
      text: giving non-citizens the right to vote in local elections?
      tag: Immigration
    -
      text: tacking if police do racial profiling, and holding them accountable if they do?
      tag: Immigration
    -
      text: limiting the number of people who get deported rather than sentenced to serve time, if convicted of a crime?
      tag: Immigration
    -
      text: the government providing or ensuring housing for LGBTQ youth facing homelessness?
      tag: LGBT
    -
      text: protecting LGBTQ people from discrimination in housing, employment, and public serving spaces/businesses like restaurants and taxis?
      tag: LGBT
    -
      text: banning anti-gay conversion "therapy"?
      tag: LGBT
    -
      text: lifting the ban on gay and bisexual men donating blood?
      tag: LGBT
    -
      text: allowing transgender youth to attend school, use facilities, and participate in programs that match the gender they identify as?
      tag: LGBT
    -
      text: nondiscrimination protections for LGBTQ people in housing, employment, and public serving spaces/businesses like restaurants and taxis?
      tag: LGBT
    -
      text: introducing small dollar public financing to decrease the influence of money in politics?
      tag: Voting Rights
    -
      text: lowering the voting age in local and municipal elections to 16?
      tag: Voting Rights
    -
      text: restoring voting rights to citizens who have been in prison, or are currently in prison?
      tag: Voting Rights
    -
      text: automatically and securely registering every eligible citizen to vote?
      tag: Voting Rights
    -
      text: offering every citizen the option to early vote, vote by mail, or register and vote on Election Day?
      tag: Voting Rights
    -
      text: a constitutional amendment overturning Citizens United and limiting private money in campaign finance?
      tag: Voting Rights
    -
      text: encouraging a culture shift to focusing on safety and justice rather than maximum punishment?
      tag: Judicial
    -
      text: ending discrimination against crime victims, regardless of the victim’s own potential criminal involvement, immigration status, etc.?
      tag: Judicial
    -
      text: developing alternatives to prosecution and incarceration?
      tag: Judicial
    -
      text: ending the practice of cash bail?
      tag: Judicial
    -
      text: tracking and making public data regarding decisions made in and by your court with defendants?
      tag: Judicial
    -
      text: providing training to your staff and encouraging an internal culture shift to focusing on safety and justice rather than maximum punishment?
      tag: Local Law Enforcement
    -
      text: formally engaging the residents of neighborhoods most affected by crime?
      tag: Local Law Enforcement
    -
      text: prohibiting discrimination against crime victims, regardless of the victim’s own potential criminal involvement, immigration status, etc.?
      tag: Local Law Enforcement
    -
      text: implementing written policies providing guidance to all deputies/officers outlining expectations around handling of arrests?
      tag: Local Law Enforcement
    -
      text: tracking, evaluating, and making public the discretionary decisions of deputies/officers in your office?
      tag: Local Law Enforcement
    -
      text: appointing independent investigators for all police-involved shootings?
      tag: Local Law Enforcement
    -
      text: bringing criminal charges against police who file false official reports?
      tag: Local Law Enforcement
    -
      text: ending arrests of low level, non-violent drug crimes?
      tag: Local Law Enforcement
    -
      text: encouraging a internal culture shift to focusing on safety and justice rather than maximum punishment?
      tag: Prosecutors
    -
      text: formally engaging the residents of neighborhoods most affected by crime?
      tag: Prosecutors
    -
      text: prohibiting discrimination against crime victims, regardless of the victim’s own potential criminal involvement, immigration status, etc.?
      tag: Prosecutors
    -
      text: implementing written policies providing guidance to all staff attorneys outlining expectations around handling of arrests?
      tag: Prosecutors
    -
      text: developing alternatives to prosecution and incarceration?
      tag: Prosecutors
    -
      text: ending the practice of charging minors as adults without oversight by a judge or a grand jury?
      tag: Prosecutors
    -
      text: tracking, evaluating, and making public the discretionary decisions of attorneys in your office?
      tag: Prosecutors
    -
      text: ending the practice of cash bail?
      tag: Prosecutors
    -
      text: appointing independent prosecutors to investigate all police-involved shootings?
      tag: Prosecutors
    -
      text: bringing criminal charges against police who file false official reports?
      tag: Prosecutors
    -
      text: ending prosecutions of low level, non-violent drug crimes?
      tag: Prosecutors

fields:
  -
    label: Title Page Header
    placeholder: The title that will appear on the front page of your guide
    element: input
    example: 2016 Chicago Voter Guide
    example_elem: h1
    limit: 40
    name: title_page_header
  -
    label: Title Page Subheader
    placeholder: The line right below the title, usually reminds people to vote
    example: Be Sure to Vote By November 8th
    element: input
    example_elem: h2
    limit: 40
    name: title_page_subheader
  -
    label: Title Page Blurb
    placeholder: A little bit about voting and the guide
    example: Your secret ballot means it’s all yours to decide. But hopefully this independent local nonprofit-prepared info helps.
    element: textarea
    limit: 120
    name: title_page_blurb
  -
    label: About Us Blurb
    placeholder: A note about your organization and what you do
    example: New Era Colorado Action Fund is a local non-partisan, non-profit organization reinventing politics for our generation through innovative social and political action. We inspire young Coloradans to move our state forward, engaging our generation in our city- and state-level democracy. New Era Colorado Action Fund is a 501(c)4 non-profit organization. You can learn more or sign up to volunteer at NewEraColoradoAction.org.
    element: textarea
    limit: 320
    name: about_us_blurb
  -
    label: Logo
    placeholder: Your logo - will need to work up to 200px
    example: /example_logo.png
    example_elem: img
    example_attr: src
    example_props:
        width: 120px
    element: ImageComponent
    name: about_us_logo
  -
    label: What You've Got to Bring To Vote
    placeholder: A paragraph explaining what you need to bring to vote
    example: To avoid issues on Election Day, or if you are a first time voter, we recommend you bring some form of identification. Options for what you can bring to prove identity and residency.
    element: textarea
    limit: 230
    name: what_you_got_to_bring
  -
    label: Where You've Got To Go
    placeholder: A paragraph explaining where you need to go to vote
    example: From February 29 through March 12, all 51 Early Voting sites will be open Monday through Saturday from 9am - 5pm. Go to chicagoelections.com to find a location near you. Please bring a government photo ID during early voting. For both “Grace Period” and “Early Voting” you will register and vote in the same day. To find polling locations for Election Day or early voting go to chicagoelections.com
    element: textarea
    limit: 450
    name: where_you_got_to_go
  -
    label: Find Out More
    placeholder: A paragraph explaining the guide and pointing to more information
    example: This independent voter guide is designed to give you the quickest, most important information on what you’re facing on your ballot and why it’s important to vote. But obviously there’s a lot more  information out there. If you’re looking to read more, we highly encourage checking out our bigger, online guide
    element: textarea
    limit: 350
    name: find_out_more
  -
    label: Partners
    placeholder: Thank the people and organizations the made this happen
    example: Also, lots more good info from our partners
    element: input
    limit: 50
    name: partners_list
  -
    label: Primary Color
    element: input
    type: color
    name: primary_color
    default: "#26aac6"
    example_elem: ColorBlob
    example_attr: color
  -
    label: Secondary Color
    element: input
    type: color
    name: secondary_color
    default: "#d81b59"
    example_elem: ColorText
    example_attr: color
  -
    label: Contest Layout
    element: SelectComponent
    options:
      -
        text: Two Page Contests
        value: contest_large
      -
        text: One Page Contests
        value: contest_small
    name: contest_layout
    default: contest_large
    example_elem: ContestType
    example_attr: partial

tags:
  - Climate
  - Criminal Justice Reform
  - Drug Policy
  - Economy
  - Education
  - Healthcare
  - Immigration
  - LGBT
  - Reproduction Rights
  - Voting Rights
