
name: Mail Voter Guide

screenshot: mail.png
view: mail
folder: archive/2016_default

available_pages: 10
filler_pages: 4

render_options:
  height: 4.25in
  width: 6.25in
  margin: 0.125in

inherits: archived/2016_default
